### ISSUE TITLE
Failure to install `mVIRs`

### ISSUE THREAD

**Issue by valentynbez** [SushiLab/OPR_Finder#5]
Python version: 3.8.0
bzip2 version : 1.0.8

After running command `pip install mvirs` within environment with installed dependencies I receive the following error:
```
Collecting mvirs
  Using cached mVIRs-1.1.1.tar.gz (37 kB)
  Preparing metadata (setup.py) ... done
Collecting pysam
  Using cached pysam-0.19.1.tar.gz (3.9 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [139 lines of output]
      # pysam: no cython available - using pre-compiled C
      # pysam: htslib mode is shared
      # pysam: HTSLIB_CONFIGURE_OPTIONS=None
      # pysam: (sysconfig) CC=gcc -pthread -B /nfs/home/vbezshapkin/miniconda3/envs/mvirs/compiler_compat -Wl,--sysroot=/
      # pysam: (sysconfig) CFLAGS=-Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes
      # pysam: (sysconfig) LDFLAGS=-L/nfs/home/vbezshapkin/miniconda3/envs/mvirs/lib -Wl,-rpath=/nfs/home/vbezshapkin/miniconda3/envs/mvirs/lib -Wl,--no-as-needed -Wl,--sysroot=/
      checking for gcc... gcc -pthread -B /nfs/home/vbezshapkin/miniconda3/envs/mvirs/compiler_compat -Wl,--sysroot=/
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether we are using the GNU C compiler... yes
      checking whether gcc -pthread -B /nfs/home/vbezshapkin/miniconda3/envs/mvirs/compiler_compat -Wl,--sysroot=/ accepts -g... yes
      checking for gcc -pthread -B /nfs/home/vbezshapkin/miniconda3/envs/mvirs/compiler_compat -Wl,--sysroot=/ option to accept ISO C89... none needed
      checking for ranlib... ranlib
      checking for grep that handles long lines and -e... /usr/bin/grep
      checking for C compiler warning flags... unknown
      checking for pkg-config... /usr/bin/pkg-config
      checking pkg-config is at least version 0.9.0... yes
      checking for special C compiler options needed for large files... no
      checking for _FILE_OFFSET_BITS value needed for large files... no
      checking shared library type for unknown-Linux... plain .so
      checking whether the compiler accepts -fvisibility=hidden... yes
      checking how to run the C preprocessor... gcc -pthread -B /nfs/home/vbezshapkin/miniconda3/envs/mvirs/compiler_compat -Wl,--sysroot=/ -E
      checking for egrep... /usr/bin/grep -E
      checking for ANSI C header files... yes
      checking for sys/types.h... yes
      checking for sys/stat.h... yes
      checking for stdlib.h... yes
      checking for string.h... yes
      checking for memory.h... yes
      checking for strings.h... yes
      checking for inttypes.h... yes
      checking for stdint.h... yes
      checking for unistd.h... yes
      checking for stdlib.h... (cached) yes
      checking for unistd.h... (cached) yes
      checking for sys/param.h... yes
      checking for getpagesize... yes
      checking for working mmap... yes
      checking for gmtime_r... yes
      checking for fsync... yes
      checking for drand48... yes
      checking for srand48_deterministic... no
      checking whether fdatasync is declared... yes
      checking for fdatasync... yes
      checking for library containing log... -lm
      checking for zlib.h... yes
      checking for inflate in -lz... yes
      checking for library containing recv... none required
      checking for bzlib.h... no
      checking for BZ2_bzBuffToBuffCompress in -lbz2... yes
      configure: error: libbzip2 development files not found

      The CRAM format may use bzip2 compression, which is implemented in HTSlib
      by using compression routines from libbzip2 <http://www.bzip.org/>.

      Building HTSlib requires libbzip2 development files to be installed on the
      build machine; you may need to ensure a package such as libbz2-dev (on Debian
      or Ubuntu Linux) or bzip2-devel (on RPM-based Linux distributions or Cygwin)
      is installed.

      Either configure with --disable-bz2 (which will make some CRAM files
      produced elsewhere unreadable) or resolve this error to build HTSlib.
      checking for gcc... gcc -pthread -B /nfs/home/vbezshapkin/miniconda3/envs/mvirs/compiler_compat -Wl,--sysroot=/
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether we are using the GNU C compiler... yes
      checking whether gcc -pthread -B /nfs/home/vbezshapkin/miniconda3/envs/mvirs/compiler_compat -Wl,--sysroot=/ accepts -g... yes
      checking for gcc -pthread -B /nfs/home/vbezshapkin/miniconda3/envs/mvirs/compiler_compat -Wl,--sysroot=/ option to accept ISO C89... none needed
      checking for ranlib... ranlib
      checking for grep that handles long lines and -e... /usr/bin/grep
      checking for C compiler warning flags... unknown
      checking for pkg-config... /usr/bin/pkg-config
      checking pkg-config is at least version 0.9.0... yes
      checking for special C compiler options needed for large files... no
      checking for _FILE_OFFSET_BITS value needed for large files... no
      checking shared library type for unknown-Linux... plain .so
      checking whether the compiler accepts -fvisibility=hidden... yes
      checking how to run the C preprocessor... gcc -pthread -B /nfs/home/vbezshapkin/miniconda3/envs/mvirs/compiler_compat -Wl,--sysroot=/ -E
      checking for egrep... /usr/bin/grep -E
      checking for ANSI C header files... yes
      checking for sys/types.h... yes
      checking for sys/stat.h... yes
      checking for stdlib.h... yes
      checking for string.h... yes
      checking for memory.h... yes
      checking for strings.h... yes
      checking for inttypes.h... yes
      checking for stdint.h... yes
      checking for unistd.h... yes
      checking for stdlib.h... (cached) yes
      checking for unistd.h... (cached) yes
      checking for sys/param.h... yes
      checking for getpagesize... yes
      checking for working mmap... yes
      checking for gmtime_r... yes
      checking for fsync... yes
      checking for drand48... yes
      checking for srand48_deterministic... no
      checking whether fdatasync is declared... yes
      checking for fdatasync... yes
      checking for library containing log... -lm
      checking for zlib.h... yes
      checking for inflate in -lz... yes
      checking for library containing recv... none required
      checking for bzlib.h... no
      checking for BZ2_bzBuffToBuffCompress in -lbz2... yes
      configure: error: libbzip2 development files not found

      The CRAM format may use bzip2 compression, which is implemented in HTSlib
      by using compression routines from libbzip2 <http://www.bzip.org/>.

      Building HTSlib requires libbzip2 development files to be installed on the
      build machine; you may need to ensure a package such as libbz2-dev (on Debian
      or Ubuntu Linux) or bzip2-devel (on RPM-based Linux distributions or Cygwin)
      is installed.

      Either configure with --disable-bz2 (which will make some CRAM files
      produced elsewhere unreadable) or resolve this error to build HTSlib.
      Makefile:122: htscodecs.mk: No such file or directory
      config.mk:2: *** Resolve configure error first.  Stop.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-tg_t_11v/pysam_72162761c7fe4404a7b02fd709decbd2/setup.py", line 375, in <module>
          htslib_make_options = run_make_print_config()
        File "/tmp/pip-install-tg_t_11v/pysam_72162761c7fe4404a7b02fd709decbd2/setup.py", line 74, in run_make_print_config
          stdout = subprocess.check_output(["make", "-s", "print-config"])
        File "/nfs/home/vbezshapkin/miniconda3/envs/mvirs/lib/python3.8/subprocess.py", line 411, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/nfs/home/vbezshapkin/miniconda3/envs/mvirs/lib/python3.8/subprocess.py", line 512, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['make', '-s', 'print-config']' returned non-zero exit status 2.
      # pysam: htslib configure options: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

**Comment by valentynbez** [comment]
Managed to resolve following the subsequent steps: 
1. Loaded bzip2 using `module load bzip2`
2. Learned `pip install pysam` fails with `python==3.8` - downgraded `python==3.7`
3. Got pysam installation error: 
```
creating build/temp.linux-x86_64-cpython-37/pysam
      gcc -pthread -B /nfs/home/vbezshapkin/miniconda3/envs/mvirs/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/tmp/pip-install-o58dw52c/pysam_e5a03d4c9d1a4ad18f23c1fb1e922126/htslib -I/tmp/pip-install-o58dw52c/pysam_e5a03d4c9d1a4ad18f23c1fb1e922126/samtools -I/tmp/pip-install-o58dw52c/pysam_e5a03d4c9d1a4ad18f23c1fb1e922126/samtools/lz4 -I/tmp/pip-install-o58dw52c/pysam_e5a03d4c9d1a4ad18f23c1fb1e922126/bcftools -I/tmp/pip-install-o58dw52c/pysam_e5a03d4c9d1a4ad18f23c1fb1e922126/pysam -I/tmp/pip-install-o58dw52c/pysam_e5a03d4c9d1a4ad18f23c1fb1e922126 -I/nfs/home/vbezshapkin/miniconda3/envs/mvirs/include/python3.7m -c htslib/bcf_sr_sort.c -o build/temp.linux-x86_64-cpython-37/htslib/bcf_sr_sort.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
      as: unrecognized option '--gdwarf-5'
```
4. Installed `pysam` using conda 
5. Run `pip install mvirs`

**Comment by valentynbez** [comment]
The final *de novo* solution is: 
```
$ conda create -n mvirs python==3.7 pip bwa samtools pysam -c bioconda 
$ conda activate mvirs
$ python -m pip install mvirs
```
